### ISSUE TITLE
It doesn't work in IE

### ISSUE THREAD

**Issue by Meshuggah14** [webislife/jQueryDatePicker#3]

**Comment by Meshuggah14** [comment]
Hi. Great work you've done, but it seems to be not work in IE :(

**Comment by Meshuggah14** [comment]
And one more idea if could start with empty value of startDate and endDate, just with placeholder value

**Comment by webislife** [comment]
Hi. Write please ie and is version.

**Comment by Meshuggah14** [comment]
version is 11.0.9600.18376IS and update ver. is 11.0.33

**Comment by webislife** [comment]
Fixed, check in demo page please
http://webislife.ru/daterangepicker/
