### ISSUE TITLE
Bug: Rendering selecting day between 1 and 9

### ISSUE THREAD

**Issue by leitocardoso** [webislife/jQueryDatePicker#4]
There is a bug in the renderMonth method. When you call moment instance, the input format is wrong and causes not to render correctly if you select any day between 1 and 9.

Line 215
Bug: 
let forDate = moment(date.format('YYYY-MM') + '-' + (i + 1));

Fix: 
let forDate = moment(date.format('YYYY-MM') + '-' + ((i + 1) < 10 ? '0' + (i + 1) : (i + 1)));

See you

**Comment by webislife** [comment]
Thanks for feedback. Fixed.
